FROM golang:1.14-alpine as builder

WORKDIR /src/
RUN apk --update add --no-cache ca-certificates openssl git tzdata && \
update-ca-certificates

COPY . .

RUN go mod download
RUN CGO_ENABLED=0 go build server/todo_server.go
RUN cp todo_server /bin/todo_server

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /bin/todo_server /bin/todo_server

WORKDIR /bin/
# CMD ["reflex", "-c" "reflex.conf"]
ENTRYPOINT ["/bin/todo_server"]
