// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package todopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TodoServiceClient interface {
	CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*Todo, error)
	TodoById(ctx context.Context, in *TodoCriteria, opts ...grpc.CallOption) (*Todo, error)
	TodoByCriteria(ctx context.Context, in *TodoCriteria, opts ...grpc.CallOption) (TodoService_TodoByCriteriaClient, error)
}

type todoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoServiceClient(cc grpc.ClientConnInterface) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := c.cc.Invoke(ctx, "/proto.TodoService/CreateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) TodoById(ctx context.Context, in *TodoCriteria, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := c.cc.Invoke(ctx, "/proto.TodoService/TodoById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) TodoByCriteria(ctx context.Context, in *TodoCriteria, opts ...grpc.CallOption) (TodoService_TodoByCriteriaClient, error) {
	stream, err := c.cc.NewStream(ctx, &TodoService_ServiceDesc.Streams[0], "/proto.TodoService/TodoByCriteria", opts...)
	if err != nil {
		return nil, err
	}
	x := &todoServiceTodoByCriteriaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TodoService_TodoByCriteriaClient interface {
	Recv() (*Todo, error)
	grpc.ClientStream
}

type todoServiceTodoByCriteriaClient struct {
	grpc.ClientStream
}

func (x *todoServiceTodoByCriteriaClient) Recv() (*Todo, error) {
	m := new(Todo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TodoServiceServer is the server API for TodoService service.
// All implementations must embed UnimplementedTodoServiceServer
// for forward compatibility
type TodoServiceServer interface {
	CreateTodo(context.Context, *CreateTodoRequest) (*Todo, error)
	TodoById(context.Context, *TodoCriteria) (*Todo, error)
	TodoByCriteria(*TodoCriteria, TodoService_TodoByCriteriaServer) error
	mustEmbedUnimplementedTodoServiceServer()
}

// UnimplementedTodoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTodoServiceServer struct {
}

func (UnimplementedTodoServiceServer) CreateTodo(context.Context, *CreateTodoRequest) (*Todo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTodo not implemented")
}
func (UnimplementedTodoServiceServer) TodoById(context.Context, *TodoCriteria) (*Todo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TodoById not implemented")
}
func (UnimplementedTodoServiceServer) TodoByCriteria(*TodoCriteria, TodoService_TodoByCriteriaServer) error {
	return status.Errorf(codes.Unimplemented, "method TodoByCriteria not implemented")
}
func (UnimplementedTodoServiceServer) mustEmbedUnimplementedTodoServiceServer() {}

// UnsafeTodoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TodoServiceServer will
// result in compilation errors.
type UnsafeTodoServiceServer interface {
	mustEmbedUnimplementedTodoServiceServer()
}

func RegisterTodoServiceServer(s grpc.ServiceRegistrar, srv TodoServiceServer) {
	s.RegisterService(&TodoService_ServiceDesc, srv)
}

func _TodoService_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TodoService/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).CreateTodo(ctx, req.(*CreateTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_TodoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TodoCriteria)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).TodoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TodoService/TodoById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).TodoById(ctx, req.(*TodoCriteria))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_TodoByCriteria_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TodoCriteria)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TodoServiceServer).TodoByCriteria(m, &todoServiceTodoByCriteriaServer{stream})
}

type TodoService_TodoByCriteriaServer interface {
	Send(*Todo) error
	grpc.ServerStream
}

type todoServiceTodoByCriteriaServer struct {
	grpc.ServerStream
}

func (x *todoServiceTodoByCriteriaServer) Send(m *Todo) error {
	return x.ServerStream.SendMsg(m)
}

// TodoService_ServiceDesc is the grpc.ServiceDesc for TodoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TodoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTodo",
			Handler:    _TodoService_CreateTodo_Handler,
		},
		{
			MethodName: "TodoById",
			Handler:    _TodoService_TodoById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TodoByCriteria",
			Handler:       _TodoService_TodoByCriteria_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/todopb/todo_server.proto",
}
